"""Virtual Lab package."""

import importlib
from typing import Any

from virtual_lab.__about__ import __version__
from virtual_lab.env_file import load_default_env, load_env

# First, so that every module imported after it sees the keys the .env file sets, as Biomni's do
load_default_env()

from virtual_lab.actions import CodeAction, find_code_action
from virtual_lab.agent import Agent
from virtual_lab.artifacts import CodeArtifacts, CodeFile, UnsafeFilenameError, save_artifacts
from virtual_lab.benchmarks import (
    Benchmark,
    BenchmarkDownload,
    BenchmarkError,
    BiomniEval1,
    BiomniEval1Benchmark,
    HumanitysLastExam,
    LabBench,
    Question,
    download_benchmarks,
)
from virtual_lab.chemistry import (
    Activity,
    ActivityResults,
    Compound,
    Drug,
    DrugHit,
    SearchHits,
    Target,
    get_activities,
    get_compound,
    get_drug,
    search_drugs,
    search_targets,
)
from virtual_lab.custom_tools import tool_from_function
from virtual_lab.databases import (
    Chain,
    DownloadedFile,
    PredictedStructure,
    Protein,
    SearchResults,
    Structure,
    download_structure,
    get_predicted_structure,
    get_protein,
    get_structure,
    search_proteins,
)
from virtual_lab.environment import (
    DATA_LAKE,
    SANDBOX_LIBRARIES,
    SANDBOX_PLATFORM,
    DataLakeDownload,
    build_sandbox_image,
    download_data_lake,
    sandbox_image,
)
from virtual_lab.evaluation import (
    Attempt,
    EvaluationReport,
    QuestionResult,
    SingleAgent,
    SolverContext,
    TeamMeeting,
    run_benchmark,
)
from virtual_lab.execution import (
    DockerExecutor,
    DockerUnavailableError,
    ExecutionError,
    ExecutionResult,
    LocalExecutor,
    UnsupportedLanguageError,
    biomni_package_directory,
    run_files,
)
from virtual_lab.llm import detect_source, get_llm
from virtual_lab.literature import (
    Article,
    ArticleResults,
    ArticleText,
    Preprint,
    PreprintResults,
    get_article,
    get_article_text,
    search_articles,
    search_preprints,
)
from virtual_lab.mcp_tools import MCPServerError, MCPToolError, MCPTools, connect_mcp
from virtual_lab.memory import Finding, Findings, LabMemory, MemoryEntry
from virtual_lab.planning import NextStep, PlanTask, ProjectReport, ProjectRound, ResearchPlan, Review, run_project
from virtual_lab.project import Project, ProjectBudgetExceededError, ProjectStateError, ProjectStep
from virtual_lab.records import DatabaseError, RecordNotFoundError
from virtual_lab.repair import (
    RepairAttempt,
    RepairOutcome,
    run_with_repair,
    save_execution_record,
)
from virtual_lab.resources import (
    KnowHow,
    Resource,
    Resources,
    available_resources,
    biomni_tools,
    commercial_data_lake,
    load_know_how,
    select_resources,
)
from virtual_lab.run_meeting import (
    MeetingResult,
    TruncatedResponseError,
    hold_meeting,
    run_meeting,
)
from virtual_lab.schemas import AgentSpec, ComponentAssignment, ImplementationPlan, TeamRoster
from virtual_lab.session import (
    CellResult,
    DockerSession,
    LocalSession,
    Session,
    SessionError,
    session_executor,
    session_tool,
    session_tools_prompt,
)
from virtual_lab.structured import StructuredOutputError
from virtual_lab.tables import (
    Column,
    DataFile,
    DataFiles,
    Table,
    TableError,
    describe_table,
    list_data_files,
)
from virtual_lab.tools import (
    ALPHAFOLD_LOOKUP_TOOL,
    ARXIV_SEARCH_TOOL,
    CHEMBL_ACTIVITIES_TOOL,
    CHEMBL_LOOKUP_TOOL,
    CHEMBL_SEARCH_TOOL,
    CHEMBL_TARGET_SEARCH_TOOL,
    DATABASE_TOOLS,
    EUROPE_PMC_FULLTEXT_TOOL,
    EUROPE_PMC_LOOKUP_TOOL,
    EUROPE_PMC_SEARCH_TOOL,
    PDB_LOOKUP_TOOL,
    PUBCHEM_LOOKUP_TOOL,
    PUBMED_TOOL,
    TOOL_REGISTRY,
    UNIPROT_LOOKUP_TOOL,
    UNIPROT_SEARCH_TOOL,
    Tool,
    all_tools,
    data_file_tools,
    structure_file_tool,
    tools_for,
)
from virtual_lab.toolbox import BiomniToolError, biomni_session_tools
from virtual_lab.utils import BudgetExceededError, CostUnknownError
from virtual_lab.web import (
    ALLOWED_HOSTS,
    DisallowedHostError,
    ResponseTooLargeError,
    WebRequestError,
    request_json,
    request_text,
)


__all__ = [
    "__version__",
    "ALLOWED_HOSTS",
    "ALPHAFOLD_LOOKUP_TOOL",
    "ARXIV_SEARCH_TOOL",
    "Activity",
    "ActivityResults",
    "Agent",
    "AgentSpec",
    "Article",
    "ArticleResults",
    "ArticleText",
    "Attempt",
    "Benchmark",
    "BenchmarkDownload",
    "BenchmarkError",
    "BiomniEval1",
    "BiomniEval1Benchmark",
    "BiomniToolError",
    "BudgetExceededError",
    "CHEMBL_ACTIVITIES_TOOL",
    "CHEMBL_LOOKUP_TOOL",
    "CHEMBL_SEARCH_TOOL",
    "CHEMBL_TARGET_SEARCH_TOOL",
    "CellResult",
    "Chain",
    "CodeAction",
    "CodeArtifacts",
    "CodeFile",
    "Column",
    "ComponentAssignment",
    "Compound",
    "CostUnknownError",
    "DATABASE_TOOLS",
    "DATA_LAKE",
    "DataFile",
    "DataFiles",
    "DataLakeDownload",
    "DatabaseError",
    "DisallowedHostError",
    "DockerExecutor",
    "DockerSession",
    "DockerUnavailableError",
    "DownloadedFile",
    "Drug",
    "DrugHit",
    "EUROPE_PMC_FULLTEXT_TOOL",
    "EUROPE_PMC_LOOKUP_TOOL",
    "EUROPE_PMC_SEARCH_TOOL",
    "EvaluationReport",
    "ExecutionError",
    "ExecutionResult",
    "Finding",
    "Findings",
    "HumanitysLastExam",
    "ImplementationPlan",
    "KnowHow",
    "LabBench",
    "LabMemory",
    "LocalExecutor",
    "LocalSession",
    "MCPServerError",
    "MCPToolError",
    "MCPTools",
    "MeetingResult",
    "MemoryEntry",
    "NextStep",
    "PDB_LOOKUP_TOOL",
    "PUBCHEM_LOOKUP_TOOL",
    "PUBMED_TOOL",
    "PlanTask",
    "PredictedStructure",
    "Project",
    "ProjectBudgetExceededError",
    "ProjectReport",
    "ProjectRound",
    "ProjectStateError",
    "ProjectStep",
    "Preprint",
    "PreprintResults",
    "Protein",
    "Question",
    "QuestionResult",
    "RecordNotFoundError",
    "RepairAttempt",
    "RepairOutcome",
    "ResearchPlan",
    "Resource",
    "Resources",
    "ResponseTooLargeError",
    "Review",
    "SANDBOX_LIBRARIES",
    "SANDBOX_PLATFORM",
    "SearchHits",
    "SearchResults",
    "Session",
    "SessionError",
    "SingleAgent",
    "SolverContext",
    "Structure",
    "StructuredOutputError",
    "TOOL_REGISTRY",
    "Table",
    "TableError",
    "Target",
    "TeamMeeting",
    "TeamRoster",
    "Tool",
    "TruncatedResponseError",
    "UNIPROT_LOOKUP_TOOL",
    "UNIPROT_SEARCH_TOOL",
    "UnsafeFilenameError",
    "UnsupportedLanguageError",
    "WebRequestError",
    "all_tools",
    "available_resources",
    "biomni_package_directory",
    "biomni_session_tools",
    "biomni_tools",
    "build_sandbox_image",
    "commercial_data_lake",
    "connect_mcp",
    "create_mcp_server",
    "data_file_tools",
    "describe_table",
    "detect_source",
    "download_benchmarks",
    "download_data_lake",
    "download_structure",
    "find_code_action",
    "get_activities",
    "get_article",
    "get_article_text",
    "get_compound",
    "get_drug",
    "get_llm",
    "get_predicted_structure",
    "get_protein",
    "get_structure",
    "hold_meeting",
    "list_data_files",
    "load_env",
    "load_know_how",
    "request_json",
    "request_text",
    "run_benchmark",
    "run_files",
    "run_meeting",
    "run_project",
    "run_with_repair",
    "sandbox_image",
    "save_artifacts",
    "save_execution_record",
    "search_articles",
    "search_drugs",
    "search_preprints",
    "search_proteins",
    "search_targets",
    "select_resources",
    "serve_mcp",
    "session_executor",
    "session_tool",
    "session_tools_prompt",
    "structure_file_tool",
    "tool_from_function",
    "tools_for",
]

# Imported when first used, so that python -m virtual_lab.mcp_server does not find the module it
# runs already imported by the package, which runpy warns of
LAZY_EXPORTS = {"create_mcp_server": "virtual_lab.mcp_server", "serve_mcp": "virtual_lab.mcp_server"}


def __getattr__(name: str) -> Any:
    if name in LAZY_EXPORTS:
        return getattr(importlib.import_module(LAZY_EXPORTS[name]), name)

    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
