"""Virtual Lab package."""

import importlib
from typing import Any

from virtual_lab.__about__ import __version__
from virtual_lab.env_file import load_default_env, load_env

# First, so that every module imported after it sees the keys the .env file sets, as Biomni's do
load_default_env()

from virtual_lab.actions import CodeAction, find_code_action
from virtual_lab.agent import Agent
from virtual_lab.approval import (
    ApprovalDeclined,
    ApprovalRequest,
    ServerQuestion,
    answer_in_terminal,
    approve_in_terminal,
)
from virtual_lab.artifacts import CodeArtifacts, CodeFile, UnsafeFilenameError, save_artifacts
from virtual_lab.benchmarks import (
    Benchmark,
    BenchmarkDownload,
    BenchmarkError,
    BiomniEval1,
    BiomniEval1Benchmark,
    HumanitysLastExam,
    LabBench,
    Question,
    download_benchmarks,
)
from virtual_lab.chemistry import (
    Activity,
    ActivityResults,
    Compound,
    Drug,
    DrugHit,
    SearchHits,
    Target,
    get_activities,
    get_compound,
    get_drug,
    search_drugs,
    search_targets,
)
from virtual_lab.custom_tools import tool_from_function
from virtual_lab.databases import (
    Chain,
    DownloadedFile,
    PredictedStructure,
    Protein,
    SearchResults,
    Structure,
    download_structure,
    get_predicted_structure,
    get_protein,
    get_structure,
    search_proteins,
)
from virtual_lab.environment import (
    DATA_LAKE,
    SANDBOX_LIBRARIES,
    SANDBOX_PLATFORM,
    DataLakeDownload,
    build_sandbox_image,
    download_data_lake,
    sandbox_image,
)
from virtual_lab.evaluation import (
    Attempt,
    EvaluationReport,
    QuestionResult,
    SingleAgent,
    SolverContext,
    TeamMeeting,
    run_benchmark,
)
from virtual_lab.events import MeetingEvent, NextTurn, ProjectEvent
from virtual_lab.export import (
    PDFExportError,
    meeting_html,
    project_html,
    save_meeting_html,
    save_meeting_pdf,
    save_project_html,
    save_project_pdf,
)
from virtual_lab.execution import (
    DockerExecutor,
    DockerUnavailableError,
    ExecutionError,
    ExecutionResult,
    LocalExecutor,
    UnsupportedLanguageError,
    biomni_package_directory,
    run_files,
)
from virtual_lab.function_checks import FunctionSourceError, read_function, script_name
from virtual_lab.function_generator import (
    FunctionBudgetExceededError,
    FunctionGenerationError,
    FunctionRunReport,
    FunctionTask,
    GeneratedFunction,
    function_tasks,
    generate_function,
    generate_functions,
    load_function,
    saved_functions,
)
from virtual_lab.function_tools import FunctionToolError, tool_from_source, tools_from_saved_functions
from virtual_lab.llm import detect_source, get_llm
from virtual_lab.literature import (
    Article,
    ArticleResults,
    ArticleText,
    Preprint,
    PreprintResults,
    get_article,
    get_article_text,
    search_articles,
    search_preprints,
)
from virtual_lab.mcp_auth import SignInError, sign_out_mcp
from virtual_lab.mcp_presets import MCP_PRESETS, MCPPreset
from virtual_lab.mcp_tools import MCPServerError, MCPToolError, MCPTools, connect_mcp
from virtual_lab.memory import Finding, Findings, LabMemory, MemoryEntry
from virtual_lab.paper_batch import (
    Paper,
    PaperResult,
    PaperRunReport,
    PaperSummary,
    PaperUnavailableError,
    SubjectsReport,
    biorxiv_papers,
    combine_paper_summaries,
    paper_text,
    papers_in,
    read_biorxiv_subjects,
    read_papers,
    summarize_papers,
)
from virtual_lab.papers import (
    PaperBudgetExceededError,
    PaperDatabase,
    PaperFindings,
    PaperReading,
    PaperReadingError,
    PaperSoftware,
    PaperTask,
    extract_paper_findings,
    read_paper,
    split_text,
)
from virtual_lab.planning import NextStep, PlanTask, ProjectReport, ProjectRound, ResearchPlan, Review, run_project
from virtual_lab.project import Project, ProjectBudgetExceededError, ProjectStateError, ProjectStep
from virtual_lab.records import DatabaseError, RecordNotFoundError
from virtual_lab.repair import (
    RepairAttempt,
    RepairOutcome,
    run_with_repair,
    save_execution_record,
)
from virtual_lab.resources import (
    KnowHow,
    Resource,
    Resources,
    available_resources,
    biomni_tools,
    commercial_data_lake,
    load_know_how,
    select_resources,
)
from virtual_lab.run_meeting import (
    MeetingResult,
    TruncatedResponseError,
    hold_meeting,
    run_meeting,
)
from virtual_lab.schemas import AgentSpec, ComponentAssignment, ImplementationPlan, TeamRoster
from virtual_lab.session import (
    CellResult,
    DockerSession,
    LocalSession,
    Session,
    SessionError,
    session_executor,
    session_tool,
    session_tools_prompt,
)
from virtual_lab.structured import StructuredOutputError
from virtual_lab.tables import (
    Column,
    DataFile,
    DataFiles,
    Table,
    TableError,
    describe_table,
    list_data_files,
)
from virtual_lab.tools import (
    ALPHAFOLD_LOOKUP_TOOL,
    ARXIV_SEARCH_TOOL,
    CHEMBL_ACTIVITIES_TOOL,
    CHEMBL_LOOKUP_TOOL,
    CHEMBL_SEARCH_TOOL,
    CHEMBL_TARGET_SEARCH_TOOL,
    DATABASE_TOOLS,
    EUROPE_PMC_FULLTEXT_TOOL,
    EUROPE_PMC_LOOKUP_TOOL,
    EUROPE_PMC_SEARCH_TOOL,
    PDB_LOOKUP_TOOL,
    PUBCHEM_LOOKUP_TOOL,
    PUBMED_TOOL,
    TOOL_REGISTRY,
    UNIPROT_LOOKUP_TOOL,
    UNIPROT_SEARCH_TOOL,
    Tool,
    all_tools,
    data_file_tools,
    structure_file_tool,
    tools_for,
)
from virtual_lab.toolbox import BiomniToolError, biomni_session_tools
from virtual_lab.utils import BudgetExceededError, CostUnknownError
from virtual_lab.web import (
    ALLOWED_HOSTS,
    DisallowedHostError,
    ResponseTooLargeError,
    WebRequestError,
    request_json,
    request_text,
)


__all__ = [
    "__version__",
    "ALLOWED_HOSTS",
    "ALPHAFOLD_LOOKUP_TOOL",
    "ARXIV_SEARCH_TOOL",
    "Activity",
    "ActivityResults",
    "Agent",
    "AgentSpec",
    "ApprovalDeclined",
    "ApprovalRequest",
    "Article",
    "ArticleResults",
    "ArticleText",
    "Attempt",
    "Benchmark",
    "BenchmarkDownload",
    "BenchmarkError",
    "BiomniEval1",
    "BiomniEval1Benchmark",
    "BiomniToolError",
    "BudgetExceededError",
    "CHEMBL_ACTIVITIES_TOOL",
    "CHEMBL_LOOKUP_TOOL",
    "CHEMBL_SEARCH_TOOL",
    "CHEMBL_TARGET_SEARCH_TOOL",
    "CellResult",
    "Chain",
    "CodeAction",
    "CodeArtifacts",
    "CodeFile",
    "Column",
    "ComponentAssignment",
    "Compound",
    "CostUnknownError",
    "DATABASE_TOOLS",
    "DATA_LAKE",
    "DataFile",
    "DataFiles",
    "DataLakeDownload",
    "DatabaseError",
    "DisallowedHostError",
    "DockerExecutor",
    "DockerSession",
    "DockerUnavailableError",
    "DownloadedFile",
    "Drug",
    "DrugHit",
    "EUROPE_PMC_FULLTEXT_TOOL",
    "EUROPE_PMC_LOOKUP_TOOL",
    "EUROPE_PMC_SEARCH_TOOL",
    "EvaluationReport",
    "ExecutionError",
    "ExecutionResult",
    "Finding",
    "Findings",
    "FunctionBudgetExceededError",
    "FunctionGenerationError",
    "FunctionRunReport",
    "FunctionSourceError",
    "FunctionTask",
    "FunctionToolError",
    "GeneratedFunction",
    "HumanitysLastExam",
    "ImplementationPlan",
    "KnowHow",
    "LabBench",
    "LabMemory",
    "LocalExecutor",
    "LocalSession",
    "MCPPreset",
    "MCPServerError",
    "MCPToolError",
    "MCPTools",
    "MCP_PRESETS",
    "MeetingEvent",
    "MeetingResult",
    "MemoryEntry",
    "NextStep",
    "NextTurn",
    "PDB_LOOKUP_TOOL",
    "Paper",
    "PaperBudgetExceededError",
    "PaperDatabase",
    "PaperFindings",
    "PaperReading",
    "PaperReadingError",
    "PaperResult",
    "PaperRunReport",
    "PaperSoftware",
    "PaperSummary",
    "PaperTask",
    "PaperUnavailableError",
    "PDFExportError",
    "PUBCHEM_LOOKUP_TOOL",
    "PUBMED_TOOL",
    "PlanTask",
    "PredictedStructure",
    "Project",
    "ProjectBudgetExceededError",
    "ProjectEvent",
    "ProjectReport",
    "ProjectRound",
    "ProjectStateError",
    "ProjectStep",
    "Preprint",
    "PreprintResults",
    "Protein",
    "Question",
    "QuestionResult",
    "RecordNotFoundError",
    "RepairAttempt",
    "RepairOutcome",
    "ResearchPlan",
    "Resource",
    "Resources",
    "ResponseTooLargeError",
    "Review",
    "SANDBOX_LIBRARIES",
    "SANDBOX_PLATFORM",
    "SearchHits",
    "SearchResults",
    "ServerQuestion",
    "Session",
    "SessionError",
    "SignInError",
    "SingleAgent",
    "SolverContext",
    "Structure",
    "StructuredOutputError",
    "SubjectsReport",
    "TOOL_REGISTRY",
    "Table",
    "TableError",
    "Target",
    "TeamMeeting",
    "TeamRoster",
    "Tool",
    "TruncatedResponseError",
    "UNIPROT_LOOKUP_TOOL",
    "UNIPROT_SEARCH_TOOL",
    "UnsafeFilenameError",
    "UnsupportedLanguageError",
    "WebRequestError",
    "all_tools",
    "answer_in_terminal",
    "approve_in_terminal",
    "available_resources",
    "biomni_package_directory",
    "biomni_session_tools",
    "biomni_tools",
    "biorxiv_papers",
    "build_sandbox_image",
    "combine_paper_summaries",
    "commercial_data_lake",
    "connect_mcp",
    "create_mcp_server",
    "data_file_tools",
    "describe_table",
    "detect_source",
    "download_benchmarks",
    "download_data_lake",
    "download_structure",
    "extract_paper_findings",
    "find_code_action",
    "function_tasks",
    "generate_function",
    "generate_functions",
    "get_activities",
    "get_article",
    "get_article_text",
    "get_compound",
    "get_drug",
    "get_llm",
    "get_predicted_structure",
    "get_protein",
    "get_structure",
    "hold_meeting",
    "list_data_files",
    "load_env",
    "load_function",
    "load_know_how",
    "meeting_html",
    "paper_text",
    "papers_in",
    "project_html",
    "read_biorxiv_subjects",
    "read_function",
    "read_paper",
    "read_papers",
    "request_json",
    "request_text",
    "run_benchmark",
    "run_files",
    "run_meeting",
    "run_project",
    "run_with_repair",
    "sandbox_image",
    "save_artifacts",
    "save_execution_record",
    "save_meeting_html",
    "save_meeting_pdf",
    "save_project_html",
    "save_project_pdf",
    "saved_functions",
    "script_name",
    "search_articles",
    "search_drugs",
    "search_preprints",
    "search_proteins",
    "search_targets",
    "select_resources",
    "serve_mcp",
    "session_executor",
    "session_tool",
    "session_tools_prompt",
    "sign_out_mcp",
    "split_text",
    "structure_file_tool",
    "summarize_papers",
    "tool_from_function",
    "tool_from_source",
    "tools_for",
    "tools_from_saved_functions",
]

# Imported when first used, so that python -m virtual_lab.mcp_server does not find the module it
# runs already imported by the package, which runpy warns of
LAZY_EXPORTS = {"create_mcp_server": "virtual_lab.mcp_server", "serve_mcp": "virtual_lab.mcp_server"}


def __getattr__(name: str) -> Any:
    if name in LAZY_EXPORTS:
        return getattr(importlib.import_module(LAZY_EXPORTS[name]), name)

    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
