"""Lookups in the scientific databases agents need during a meeting.

Each lookup is an ordinary function with named arguments, and each returns a record with a
report() method that renders it for a model. The division matters: the record holds everything
the service returned that is worth keeping, while the report holds only what is worth paying for
in a request, which for a sequence of 35,000 residues is not the sequence.

Queries are assembled here from named arguments rather than generated by a model. A model asked
to write a query payload can write one that is subtly wrong, and the failure arrives as an empty
result rather than as an error, which is the hardest kind to notice. The cost of that is a
function signature per database, which is also the thing that makes these testable.

Requests go through virtual_lab.web, so the host allowlist, the rate limits, the size caps, and
the retries apply to everything here.
"""

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from virtual_lab.artifacts import UnsafeFilenameError, check_filename
from virtual_lab.constants import (
    MAX_CHAINS_REPORTED,
    MAX_COMMENT_CHARACTERS,
    MAX_COMMENTS_REPORTED,
    MAX_FEATURES_REPORTED,
    MAX_ITEMS_LISTED,
    MAX_SEARCH_RESULTS,
    MAX_SEQUENCE_RESIDUES_REPORTED,
    MAX_STRUCTURE_FILE_BYTES,
    MAX_URL_CHARACTERS,
)
from virtual_lab.records import (
    NO_SUCH_RECORD_STATUSES,
    RecordNotFoundError,
    as_dict,
    as_int,
    as_list,
    as_text,
    bounded,
    listing,
    number_or_none,
    truncate_text,
)
from virtual_lab.web import WebRequestError, build_url, request_json, request_text


# Feature types worth showing, in the order they are shown. A protein record carries dozens of
# kinds of annotation, most of which describe the evidence rather than the molecule. These are
# the ones that constrain a design: where the chains are cut, what is bound, what is joined.
REPORTED_FEATURE_TYPES = (
    "Signal",
    "Chain",
    "Peptide",
    "Domain",
    "Region",
    "Motif",
    "Active site",
    "Binding site",
    "Site",
    "Disulfide bond",
    "Glycosylation",
    "Modified residue",
    "Mutagenesis",
)

# The shape of a UniProt accession, as UniProt documents it. A downloaded prediction is named
# after one, so it is checked before it becomes part of a file name.
UNIPROT_ACCESSION = re.compile(
    r"[OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9](?:[A-Z][A-Z0-9]{2}[0-9]){1,2}"
)

# Comment types worth showing, in the order they are shown
REPORTED_COMMENT_TYPES = (
    "FUNCTION",
    "SUBUNIT",
    "SUBCELLULAR LOCATION",
    "DOMAIN",
    "CATALYTIC ACTIVITY",
    "DISEASE",
    "BIOTECHNOLOGY",
)


def truncate_sequence(sequence: str, limit: int = MAX_SEQUENCE_RESIDUES_REPORTED) -> str:
    """Shortens a sequence for display, saying so rather than trailing off silently.

    :param sequence: The full sequence.
    :param limit: The most residues to show.
    :return: The sequence, or its start with a note of how much was left out.
    """
    if len(sequence) <= limit:
        return sequence

    return f"{sequence[:limit]}... [{len(sequence) - limit:,} of {len(sequence):,} residues not shown]"


def wrap_sequence(sequence: str, width: int = 60) -> str:
    """Breaks a sequence into lines, as every sequence format does, so it stays readable."""
    return "\n".join(sequence[start : start + width] for start in range(0, len(sequence), width))


def first_text(comment: dict[str, Any]) -> str:
    """Returns the text of a UniProt comment, which nests it two levels down."""
    texts = as_list(comment.get("texts"))

    if not texts:
        return ""

    # Kept whole, because the report shortens each comment and would otherwise shorten it twice
    return as_text(as_dict(texts[0]).get("value"), limit=None)


def features_from(raw: list[dict[str, Any]]) -> tuple[tuple[str, str, str], ...]:
    """Selects the annotated positions worth reporting, a kind at a time.

    A well studied protein carries far more eligible features than the cap allows: p53 has 99.
    Taking the first 25 in the order the service returns them takes whatever is near the start of
    the sequence, which for p53 is 21 interaction regions and not one binding site. Taking them
    a kind at a time instead means every kind of annotation the protein has appears before any
    kind gets a second entry, so the cap costs detail rather than whole categories.

    :param raw: The features as UniProt returned them.
    :return: The features to report, as type, position, and description.
    """
    by_type: dict[str, list[tuple[str, str, str]]] = {kind: [] for kind in REPORTED_FEATURE_TYPES}

    for feature in (item for item in raw if isinstance(item, dict)):
        kind = as_text(feature.get("type"))

        if kind in by_type:
            by_type[kind].append((kind, position_of(feature), as_text(feature.get("description"))))

    deepest = max((len(found) for found in by_type.values()), default=0)
    selected = [
        found[depth]
        for depth in range(deepest)
        for found in (by_type[kind] for kind in REPORTED_FEATURE_TYPES)
        if depth < len(found)
    ]

    return tuple(selected[:MAX_FEATURES_REPORTED])


def position_of(feature: dict[str, Any]) -> str:
    """Describes where a feature is, as a position or a range."""
    location = as_dict(feature.get("location"))
    start = as_int(as_dict(location.get("start")).get("value"))
    end = as_int(as_dict(location.get("end")).get("value"))

    if start is None and end is None:
        return "?"

    if start == end:
        return str(start)

    # UniProt reports a terminus it never determined as a null value with an UNKNOWN modifier, so
    # one end of a range can be missing while the other is exact. Writing that as "None-1465"
    # reads as a parsing failure; UniProt itself writes "?-1465"
    return f"{'?' if start is None else start}-{'?' if end is None else end}"


@dataclass(frozen=True)
class Protein:
    """A protein record from UniProt.

    :param accession: The UniProt accession, which is the stable identifier for the entry.
    :param entry_name: The mnemonic entry name, such as INS_HUMAN.
    :param name: The recommended protein name.
    :param organism: The scientific name of the organism.
    :param taxon_id: The NCBI taxonomy identifier.
    :param genes: The gene names for this protein.
    :param sequence: The full amino acid sequence.
    :param length: The number of residues.
    :param mass: The molecular weight in daltons.
    :param reviewed: Whether the entry has been curated rather than generated automatically.
    :param comments: Selected free text annotations, keyed by type.
    :param features: Annotated positions, as type, position, and description.
    :param pdb_ids: PDB entries that contain this protein.
    """

    accession: str
    entry_name: str
    name: str
    organism: str
    taxon_id: int | None
    genes: tuple[str, ...]
    sequence: str
    length: int
    mass: float | None
    reviewed: bool
    comments: tuple[tuple[str, str], ...] = ()
    features: tuple[tuple[str, str, str], ...] = ()
    pdb_ids: tuple[str, ...] = ()

    def report(self) -> str:
        """Renders the record for a model."""
        lines = [
            f"UniProt {self.accession} ({self.entry_name})"
            f"{'' if self.reviewed else ' [unreviewed, annotated automatically]'}",
            f"Name: {self.name or 'not stated'}",
            f"Organism: {self.organism or 'not stated'}"
            f"{f' (taxon {self.taxon_id})' if self.taxon_id else ''}",
        ]

        if self.genes:
            lines.append(f"Genes: {listing(self.genes, MAX_ITEMS_LISTED)}")

        lines.append(
            f"Length: {self.length:,} residues"
            f"{f', {self.mass:,.0f} Da' if self.mass else ''}"
        )

        if self.pdb_ids:
            shown = self.pdb_ids[:MAX_CHAINS_REPORTED]
            remaining = len(self.pdb_ids) - len(shown)
            lines.append(
                f"PDB structures: {', '.join(shown)}"
                f"{f' and {remaining} more' if remaining > 0 else ''}"
            )

        for comment_type, text in self.comments[:MAX_COMMENTS_REPORTED]:
            lines.append(
                f"\n{comment_type.title()}: {truncate_text(text, MAX_COMMENT_CHARACTERS)}"
            )

        remaining_comments = len(self.comments) - MAX_COMMENTS_REPORTED

        if remaining_comments > 0:
            lines.append(f"\nand {remaining_comments} more annotation(s) not shown")

        if self.features:
            lines.append("\nAnnotated positions:")
            lines.extend(
                f"  {position:>12}  {kind}{f': {description}' if description else ''}"
                for kind, position, description in self.features
            )

        lines.append(f"\nSequence:\n{wrap_sequence(truncate_sequence(self.sequence))}")

        return "\n".join(lines)


@dataclass(frozen=True)
class ProteinHit:
    """One result of a UniProt search."""

    accession: str
    entry_name: str
    name: str
    organism: str
    length: int
    reviewed: bool

    def summary(self) -> str:
        """Renders one line describing this hit."""
        return (
            f"{self.accession:<12} {self.length:>6} aa  "
            f"{'reviewed  ' if self.reviewed else 'unreviewed'}  "
            f"{self.name or self.entry_name} [{self.organism or 'unknown organism'}]"
        )


@dataclass(frozen=True)
class SearchResults:
    """The results of a database search.

    :param query: The query that was run, so a report says what was asked.
    :param hits: The results, in the order the service returned them.
    """

    query: str
    hits: tuple[ProteinHit, ...]

    def report(self) -> str:
        """Renders the results for a model."""
        if not self.hits:
            return (
                f'No UniProt entries matched "{self.query}". '
                f"Try fewer terms, or a gene or protein name rather than a description."
            )

        lines = [f'{len(self.hits)} UniProt entries matching "{self.query}":']
        lines.extend(f"  {hit.summary()}" for hit in self.hits)
        # Said plainly because the ranking invites the opposite assumption. UniProt free text
        # searches an entry's references too, so a protein studied with a nanobody ranks for
        # "nanobody" above an actual nanobody sequence.
        lines.append(
            "\nThese are ranked by UniProt's own relevance, which searches an entry's references "
            "as well as the protein itself, so a top hit may only be mentioned alongside the term "
            "rather than being an example of it. Check the names before relying on one."
        )
        lines.append("Look up an accession for its sequence, function, and annotations.")

        return "\n".join(lines)


@dataclass(frozen=True)
class Chain:
    """One polymer chain of a structure."""

    entity_id: str
    description: str
    chain_ids: tuple[str, ...]
    organism: str
    sequence: str
    copies: int

    @property
    def label(self) -> str:
        """Names the chain by its strand identifiers, which an assembly of copies has dozens of."""
        return listing(self.chain_ids, MAX_ITEMS_LISTED, separator="/") or self.entity_id

    def summary(self) -> str:
        """Renders one line describing this chain."""
        return (
            f"  Chain {self.label}: {self.description or 'unnamed'}"
            f" ({len(self.sequence):,} aa"
            f"{f', {self.copies} copies' if self.copies > 1 else ''}"
            f"{f', {self.organism}' if self.organism else ''})"
        )


@dataclass(frozen=True)
class Structure:
    """An experimentally determined structure from the PDB.

    :param pdb_id: The four character PDB identifier.
    :param title: The title the depositors gave it.
    :param method: How it was determined, such as X-ray diffraction.
    :param resolution: The resolution in angstroms, where the method has one.
    :param released: The date it was first released.
    :param chains: The polymer chains that were fetched, which for a large assembly is fewer than
        the structure has.
    :param entity_count: How many distinct polymer chains the structure has in total.
    :param ligand_ids: The chemical components bound in it.
    :param pubmed_id: The article describing it.
    """

    pdb_id: str
    title: str
    method: str
    resolution: float | None
    released: str
    chains: tuple[Chain, ...] = ()
    entity_count: int | None = None
    ligand_ids: tuple[str, ...] = ()
    pubmed_id: int | None = None

    @property
    def chain_count(self) -> int:
        """How many distinct polymer chains the structure has, fetched or not."""
        return len(self.chains) if self.entity_count is None else self.entity_count

    @property
    def chains_not_shown(self) -> int:
        """How many of the structure's chains the report leaves out."""
        return max(self.chain_count - min(len(self.chains), MAX_CHAINS_REPORTED), 0)

    def report(self) -> str:
        """Renders the structure for a model."""
        lines = [
            f"PDB {self.pdb_id}: {self.title}",
            f"Method: {self.method or 'not stated'}"
            f"{f', {self.resolution} A resolution' if self.resolution else ''}",
        ]

        if self.released:
            lines.append(f"Released: {self.released}")

        if self.chains:
            shown = self.chains[:MAX_CHAINS_REPORTED]
            # The count is the structure's own, not the number that happened to be fetched: a
            # ribosome has dozens of entities and only the first few are retrieved, so counting
            # the tuple would tell an agent a 56 chain assembly is an 8 chain one
            lines.append(f"\n{self.chain_count} polymer chain(s):")
            lines.extend(chain.summary() for chain in shown)

            if self.chains_not_shown:
                lines.append(f"  and {self.chains_not_shown} more, not fetched")

        if self.ligand_ids:
            lines.append(f"\nBound components: {listing(self.ligand_ids, MAX_ITEMS_LISTED)}")

        if self.pubmed_id:
            lines.append(f"Described in PubMed {self.pubmed_id}")

        for chain in self.chains[:MAX_CHAINS_REPORTED]:
            if chain.sequence:
                lines.append(
                    f"\nSequence of chain {chain.label}:\n"
                    f"{wrap_sequence(truncate_sequence(chain.sequence))}"
                )

        return "\n".join(lines)


@dataclass(frozen=True)
class PredictedStructure:
    """A predicted structure from the AlphaFold database.

    :param accession: The UniProt accession the prediction is for.
    :param name: The protein's description.
    :param organism: The scientific name of the organism.
    :param sequence: The sequence that was modelled.
    :param mean_plddt: The average per residue confidence, from 0 to 100.
    :param version: Which release of the model this is.
    :param fraction_confident: The proportion of residues modelled with pLDDT over 70.
    :param pdb_url: Where the model can be downloaded in PDB format.
    :param cif_url: Where the model can be downloaded in mmCIF format.
    """

    accession: str
    name: str
    organism: str
    sequence: str
    mean_plddt: float | None
    version: int | None
    fraction_confident: float | None
    pdb_url: str
    cif_url: str

    @property
    def confidence(self) -> str:
        """Describes what the confidence score means, since the number alone misleads.

        A prediction with a low score is not a worse picture of the same thing. For a protein
        that is disordered, or one modelled without its partners, it is a statement that the
        structure is not defined in isolation, and building on it as though it were a structure
        is a mistake this makes visible.
        """
        if self.mean_plddt is None:
            return "confidence not reported"

        if self.mean_plddt >= 90:
            return "very high confidence, backbone and side chains likely accurate"

        if self.mean_plddt >= 70:
            return "confident backbone, side chain positions less certain"

        if self.mean_plddt >= 50:
            return "low confidence, treat as a rough topology and not as a structure"

        return (
            "very low confidence, which usually means the region is disordered or is only "
            "structured together with a partner that was not modelled"
        )

    def report(self) -> str:
        """Renders the prediction for a model."""
        lines = [
            f"AlphaFold prediction for {self.accession}"
            f"{f' (version {self.version})' if self.version else ''}",
            f"Name: {self.name or 'not stated'}",
            f"Organism: {self.organism or 'not stated'}",
            f"Length: {len(self.sequence):,} residues",
        ]

        if self.mean_plddt is not None:
            lines.append(f"Mean pLDDT: {self.mean_plddt:.1f} ({self.confidence})")

        if self.fraction_confident is not None:
            lines.append(f"Residues at pLDDT over 70: {self.fraction_confident:.0%}")

        lines.append(
            "\nThis is a prediction, not a measurement. Where an experimental structure exists "
            "in the PDB, prefer it."
        )
        lines.append(f"\nSequence:\n{wrap_sequence(truncate_sequence(self.sequence))}")

        return "\n".join(lines)


@dataclass(frozen=True)
class DownloadedFile:
    """A file fetched for code to read.

    Code an agent writes runs without network access, so a file it needs is fetched outside the
    sandbox and left in the directory that is mounted into it.

    :param path: Where the file was written.
    :param source_url: Where it came from.
    :param characters: How much was written.
    :param read_as: The path to open from the directory the code runs in.
    """

    path: Path
    source_url: str
    characters: int
    read_as: str = ""

    def report(self) -> str:
        """Renders the download for a model."""
        return (
            f"Downloaded {self.source_url}\n"
            f"Saved to {self.path} ({self.characters:,} characters).\n"
            f'Read it from code as "{self.read_as or self.path.name}".'
        )


def get_protein(accession: str) -> Protein:
    """Looks up a protein in UniProt by accession.

    :param accession: A UniProt accession, such as P01308.
    :raises RecordNotFoundError: If no entry has that accession.
    :raises WebRequestError: If UniProt cannot be reached.
    :return: The protein record.
    """
    url = build_url("https://rest.uniprot.org/uniprotkb/{accession}.json", accession=accession)

    try:
        entry = request_json(url)
    except WebRequestError as error:
        if error.status_code not in NO_SUCH_RECORD_STATUSES:
            raise

        raise RecordNotFoundError(
            f'No UniProt entry for "{accession}". Accessions look like P01308 or A0A0F6YEF6; '
            f"search by name if you do not have one."
        ) from error

    entry = as_dict(entry)

    # A withdrawn accession comes back as 200 with a stub in place of the entry, which parses
    # into a plausible looking protein of zero residues. A model proposing an accession it
    # remembers from an older paper hits this, so it has to be an error rather than a record
    if entry.get("entryType") == "Inactive":
        reason = as_dict(entry.get("inactiveReason"))
        merged_into = listing(
            [as_text(value) for value in as_list(reason.get("mergeDemergeTo"))], MAX_ITEMS_LISTED
        )

        raise RecordNotFoundError(
            f'UniProt entry "{accession}" is no longer active '
            f'({(as_text(reason.get("inactiveReasonType")) or "withdrawn").lower()})'
            f"{f'; it became {merged_into}' if merged_into else ''}."
        )

    return protein_from(entry)


def protein_from(entry: dict[str, Any]) -> Protein:
    """Builds a protein record from a UniProt entry.

    Separate from the request so that the shape of the response is tested without one, and so a
    search result, which carries the same shape, can be read by the same code.

    :param entry: The entry as UniProt returns it.
    :return: The protein record.
    """
    description = as_dict(entry.get("proteinDescription"))
    recommended = as_dict(as_dict(description.get("recommendedName")).get("fullName"))
    submitted = as_list(description.get("submissionNames"))
    held = as_dict(entry.get("sequence"))
    # Not shortened, unlike every other field: the whole sequence stays on the record for code,
    # and the report cuts it to what is worth showing
    sequence = held.get("value") if isinstance(held.get("value"), str) else ""
    organism = as_dict(entry.get("organism"))

    if recommended.get("value"):
        name = as_text(recommended["value"])
    elif submitted:
        name = as_text(as_dict(as_dict(submitted[0]).get("fullName")).get("value"))
    else:
        name = ""

    comments = tuple(
        (comment_type, first_text(comment))
        for comment_type in REPORTED_COMMENT_TYPES
        for comment in as_list(entry.get("comments"))
        if isinstance(comment, dict)
        and comment.get("commentType") == comment_type
        and first_text(comment)
    )

    features = features_from(as_list(entry.get("features")))

    pdb_ids = tuple(
        as_text(reference.get("id"))
        for reference in as_list(entry.get("uniProtKBCrossReferences"))
        if isinstance(reference, dict)
        and reference.get("database") == "PDB"
        and reference.get("id")
    )

    return Protein(
        accession=as_text(entry.get("primaryAccession")),
        entry_name=as_text(entry.get("uniProtkbId")),
        name=name,
        organism=as_text(organism.get("scientificName")),
        taxon_id=as_int(organism.get("taxonId")),
        genes=tuple(
            as_text(as_dict(gene.get("geneName")).get("value"))
            for gene in as_list(entry.get("genes"))
            if isinstance(gene, dict) and as_dict(gene.get("geneName")).get("value")
        ),
        sequence=sequence,
        length=as_int(held.get("length")) or len(sequence),
        mass=number_or_none(held.get("molWeight")),
        # UniProtKB/Swiss-Prot is curated; TrEMBL is not, and the difference matters when an
        # agent is about to build on an annotation
        reviewed=entry.get("entryType") == "UniProtKB reviewed (Swiss-Prot)",
        comments=comments,
        features=features,
        pdb_ids=pdb_ids,
    )


def search_proteins(
    query: str,
    limit: int = 10,
    reviewed_only: bool = False,
) -> SearchResults:
    """Searches UniProt for proteins matching a query.

    :param query: Free text, or UniProt query syntax such as "gene:INS AND organism_id:9606".
    :param limit: The most results to return.
    :param reviewed_only: Whether to restrict results to curated Swiss-Prot entries. This is off
        by default, and deliberately: curation covers a small fraction of UniProt, and for whole
        classes of sequence it covers none of it. A search for a nanobody with this set returns
        entries whose reference titles happen to mention one, while every real camelid VHH
        sequence is filtered out for being uncurated.
    :raises ValueError: If the limit is below one.
    :raises WebRequestError: If UniProt cannot be reached.
    :return: The matching entries.
    """
    size = bounded(limit, MAX_SEARCH_RESULTS, "limit")
    # Composed here rather than by a model. A model asked for a query string writes a plausible
    # one whose mistakes come back as an empty result rather than as an error.
    full_query = f"({query}) AND reviewed:true" if reviewed_only else query

    response = request_json(
        "https://rest.uniprot.org/uniprotkb/search",
        params={
            "query": full_query,
            "size": size,
            "format": "json",
            "fields": "accession,id,protein_name,organism_name,length,reviewed",
        },
    )

    hits = tuple(
        ProteinHit(
            accession=protein.accession,
            entry_name=protein.entry_name,
            name=protein.name,
            organism=protein.organism,
            length=protein.length,
            reviewed=protein.reviewed,
        )
        for protein in (
            protein_from(as_dict(result)) for result in as_list(as_dict(response).get("results"))
        )
    )

    return SearchResults(query=query, hits=hits)


def get_structure(pdb_id: str, include_sequences: bool = True) -> Structure:
    """Looks up an experimentally determined structure in the PDB.

    :param pdb_id: A four character PDB identifier, such as 4HHB.
    :param include_sequences: Whether to fetch the sequence of each chain, which costs one
        request per chain.
    :raises RecordNotFoundError: If no entry has that identifier.
    :raises WebRequestError: If the PDB cannot be reached.
    :return: The structure record.
    """
    identifier = pdb_id.strip().upper()
    url = build_url("https://data.rcsb.org/rest/v1/core/entry/{pdb_id}", pdb_id=identifier)

    try:
        entry = request_json(url)
    except WebRequestError as error:
        if error.status_code not in NO_SUCH_RECORD_STATUSES:
            raise

        raise RecordNotFoundError(
            f'No PDB entry for "{pdb_id}". Identifiers are four characters, such as 4HHB.'
        ) from error

    entry = as_dict(entry)
    identifiers = as_dict(entry.get("rcsb_entry_container_identifiers"))
    entity_ids = tuple(as_text(value) for value in as_list(identifiers.get("polymer_entity_ids")))
    chains: tuple[Chain, ...] = ()

    if include_sequences and entity_ids:
        chains = tuple(
            chain
            for chain in (
                get_chain(identifier, entity_id) for entity_id in entity_ids[:MAX_CHAINS_REPORTED]
            )
            if chain is not None
        )

    methods = tuple(
        as_text(item.get("method"))
        for item in as_list(entry.get("exptl"))
        if isinstance(item, dict) and item.get("method")
    )
    information = as_dict(entry.get("rcsb_entry_info"))
    resolutions = as_list(information.get("resolution_combined"))
    released = as_text(as_dict(entry.get("rcsb_accession_info")).get("initial_release_date"))

    return Structure(
        pdb_id=identifier,
        title=as_text(as_dict(entry.get("struct")).get("title")),
        method=listing(methods, MAX_ITEMS_LISTED),
        resolution=number_or_none(resolutions[0]) if resolutions else None,
        # The date carries a time and a zone that nothing here needs
        released=released.split("T")[0],
        chains=chains,
        entity_count=len(entity_ids),
        ligand_ids=tuple(
            as_text(value) for value in as_list(information.get("nonpolymer_bound_components"))
        ),
        pubmed_id=as_int(identifiers.get("pubmed_id")),
    )


def get_chain(pdb_id: str, entity_id: str) -> Chain | None:
    """Looks up one polymer chain of a structure.

    :param pdb_id: The PDB identifier.
    :param entity_id: The polymer entity identifier within that structure.
    :return: The chain, or None if it cannot be read, since one missing chain should not discard
        the rest of a structure.
    """
    url = build_url(
        "https://data.rcsb.org/rest/v1/core/polymer_entity/{pdb_id}/{entity_id}",
        pdb_id=pdb_id,
        entity_id=entity_id,
    )

    try:
        entity = request_json(url)
    except WebRequestError:
        return None

    entity = as_dict(entity)
    polymer = as_dict(entity.get("entity_poly"))
    described = as_dict(entity.get("rcsb_polymer_entity"))
    sources = as_list(entity.get("rcsb_entity_source_organism"))
    strand_ids = polymer.get("pdbx_strand_id")
    strands = strand_ids.split(",") if isinstance(strand_ids, str) else []
    sequence = polymer.get("pdbx_seq_one_letter_code_can")

    return Chain(
        entity_id=str(entity_id),
        description=as_text(described.get("pdbx_description")),
        chain_ids=tuple(as_text(part) for part in strands if part),
        organism=as_text(as_dict(sources[0]).get("scientific_name")) if sources else "",
        # The canonical form spells modified residues as their standard equivalents, which is
        # what anything downstream of this expects to align against
        sequence=sequence if isinstance(sequence, str) else "",
        copies=as_int(described.get("pdbx_number_of_molecules")) or 1,
    )


def get_predicted_structure(accession: str) -> PredictedStructure:
    """Looks up a predicted structure in the AlphaFold database.

    :param accession: A UniProt accession, such as P01308.
    :raises RecordNotFoundError: If there is no prediction for that accession.
    :raises WebRequestError: If AlphaFold cannot be reached.
    :return: The prediction.
    """
    url = build_url("https://alphafold.ebi.ac.uk/api/prediction/{accession}", accession=accession)

    try:
        predictions = request_json(url)
    except WebRequestError as error:
        if error.status_code not in NO_SUCH_RECORD_STATUSES:
            raise

        raise RecordNotFoundError(
            f'No AlphaFold prediction for "{accession}". The database covers UniProt entries, '
            f"so this needs an accession such as P01308."
        ) from error

    # The endpoint answers with a list of models. Anything else is a service that has changed
    # shape, and indexing it blindly turns that into a KeyError the agent cannot act on
    if not isinstance(predictions, list) or not predictions:
        raise RecordNotFoundError(f'No AlphaFold prediction for "{accession}".')

    prediction = as_dict(predictions[0])
    # A prediction where nothing is confidently modelled reports 0.0 for both bands, which is a
    # fact worth stating rather than a missing field. Treating it as absent hides the disordered
    # protein, which is the case a confidence figure exists for
    bands = tuple(
        band
        for key in ("fractionPlddtConfident", "fractionPlddtVeryHigh")
        if (band := number_or_none(prediction.get(key))) is not None
    )
    confident = sum(bands) if bands else None
    sequence = prediction.get("uniprotSequence")

    return PredictedStructure(
        accession=as_text(prediction.get("uniprotAccession")) or accession,
        name=as_text(prediction.get("uniprotDescription")),
        organism=as_text(prediction.get("organismScientificName")),
        sequence=sequence if isinstance(sequence, str) else "",
        mean_plddt=number_or_none(prediction.get("globalMetricValue")),
        version=as_int(prediction.get("latestVersion")),
        fraction_confident=confident,
        pdb_url=as_text(prediction.get("pdbUrl"), limit=MAX_URL_CHARACTERS),
        cif_url=as_text(prediction.get("cifUrl"), limit=MAX_URL_CHARACTERS),
    )


def download_structure(
    identifier: str,
    save_dir: Path,
    source: str = "pdb",
    file_format: str = "cif",
    working_dir: Path | None = None,
) -> DownloadedFile:
    """Fetches a structure file and writes it where sandboxed code can read it.

    A structure file is for code, not for a model: a single moderate one runs to hundreds of
    kilobytes, and the sandbox that runs the code has no network of its own. So the file is
    fetched here and left in the directory mounted into it.

    :param identifier: A PDB identifier, or a UniProt accession when the source is alphafold.
    :param save_dir: The directory to write into, chosen by the caller and never by a model.
    :param source: Either "pdb" for an experimental structure or "alphafold" for a prediction.
    :param file_format: Either "cif" or "pdb".
    :param working_dir: The directory the code that reads the file will run in, so the report can
        say how to open it from there. Without it the report gives the absolute path.
    :raises ValueError: If the source or format is not one of the values above.
    :raises RecordNotFoundError: If the structure does not exist.
    :raises WebRequestError: If the file cannot be fetched.
    :return: Where the file was written.
    """
    if file_format not in {"cif", "pdb"}:
        raise ValueError(f'file_format must be "cif" or "pdb", not "{file_format}"')

    if source == "pdb":
        url = build_url(
            "https://files.rcsb.org/download/{name}",
            name=f"{identifier.strip().upper()}.{file_format}",
        )
        # Named from the built URL rather than from the argument, so the name on disk is the name
        # of the thing that was actually fetched, encoded the same way
        name = url.rsplit("/", 1)[-1]
    elif source == "alphafold":
        accession = identifier.strip().upper()

        if not UNIPROT_ACCESSION.fullmatch(accession):
            raise ValueError(
                f'"{truncate_text(identifier, 40)}" is not a UniProt accession, such as P01308'
            )

        # Asked for rather than assembled: the file name carries a model version, and guessing it
        # produces a URL that looks right and 404s
        prediction = get_predicted_structure(accession=accession)
        url = prediction.cif_url if file_format == "cif" else prediction.pdb_url

        if not url:
            raise RecordNotFoundError(
                f'AlphaFold has no {file_format} file for "{identifier}".'
            )

        # Named after the accession that was asked for, in AlphaFold's own pattern, and not after
        # the URL. The URL comes from the response, so a file name taken from it is chosen by the
        # service: one ending in /solve.py would overwrite the code the meeting is about to run.
        version = f"-model_v{prediction.version}" if prediction.version else ""
        name = f"AF-{accession}-F1{version}.{file_format}"
    else:
        raise ValueError(f'source must be "pdb" or "alphafold", not "{source}"')

    try:
        content = request_text(url, max_bytes=MAX_STRUCTURE_FILE_BYTES, use_cache=False)
    except WebRequestError as error:
        raise RecordNotFoundError(
            f'Could not download a {file_format} file for "{identifier}" from {source}: {error}'
        ) from error

    base_dir = save_dir.resolve()
    base_dir.mkdir(parents=True, exist_ok=True)

    # Checked and re-checked after resolution, the same way a meeting's own files are, because
    # the identifier in the name came from a model
    path = (base_dir / check_filename(name)).resolve()

    if not path.is_relative_to(base_dir):
        raise UnsafeFilenameError(f"Refusing to write {path}, which is outside {base_dir}")

    path.write_text(content, encoding="utf-8")

    # How to open it from the directory the code will run in, which is not the directory it was
    # written to. Telling a model the bare filename is only right when the two coincide
    if working_dir is not None and path.is_relative_to(working_dir.resolve()):
        read_as = str(path.relative_to(working_dir.resolve()))
    else:
        read_as = str(path)

    return DownloadedFile(
        path=path, source_url=url, characters=len(content), read_as=read_as
    )
